# coding: utf-8

"""
    The Weather Company PWS API

    APIs for Personal Weather Station Contributors. This is an unofficial Swagger 2.0 document for working with The Weather Company (Weather Underground) API data. At this time (23-06-2020) this document only covers 2 availible endpoints in observations domain portfolio.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pws_observations_api import PWSObservationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPWSObservationsApi(unittest.TestCase):
    """PWSObservationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.pws_observations_api.PWSObservationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_observations_all_one_day(self):
        """Test case for observations_all_one_day

        """
        pass

    def test_observations_current(self):
        """Test case for observations_current

        """
        pass


if __name__ == '__main__':
    unittest.main()
