/*
 * The Weather Company PWS API
 * APIs for Personal Weather Station Contributors. This is an unofficial Swagger 2.0 document for working with The Weather Company (Weather Underground) API data. At this time (24-06-2020) this document only covers 4 availible endpoints in observations domain portfolio.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheWeatherCompanyPwsApi);
  }
}(this, function(expect, TheWeatherCompanyPwsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SummariesInner', function() {
      beforeEach(function() {
        instance = new TheWeatherCompanyPwsApi.SummariesInner();
      });

      it('should create an instance of SummariesInner', function() {
        // TODO: update the code to test SummariesInner
        expect(instance).to.be.a(TheWeatherCompanyPwsApi.SummariesInner);
      });

      it('should have the property epoch (base name: "epoch")', function() {
        // TODO: update the code to test the property epoch
        expect(instance).to.have.property('epoch');
        // expect(instance.epoch).to.be(expectedValueLiteral);
      });

      it('should have the property humidityAvg (base name: "humidityAvg")', function() {
        // TODO: update the code to test the property humidityAvg
        expect(instance).to.have.property('humidityAvg');
        // expect(instance.humidityAvg).to.be(expectedValueLiteral);
      });

      it('should have the property humidityHigh (base name: "humidityHigh")', function() {
        // TODO: update the code to test the property humidityHigh
        expect(instance).to.have.property('humidityHigh');
        // expect(instance.humidityHigh).to.be(expectedValueLiteral);
      });

      it('should have the property humidityLow (base name: "humidityLow")', function() {
        // TODO: update the code to test the property humidityLow
        expect(instance).to.have.property('humidityLow');
        // expect(instance.humidityLow).to.be(expectedValueLiteral);
      });

      it('should have the property lat (base name: "lat")', function() {
        // TODO: update the code to test the property lat
        expect(instance).to.have.property('lat');
        // expect(instance.lat).to.be(expectedValueLiteral);
      });

      it('should have the property lon (base name: "lon")', function() {
        // TODO: update the code to test the property lon
        expect(instance).to.have.property('lon');
        // expect(instance.lon).to.be(expectedValueLiteral);
      });

      it('should have the property obsTimeLocal (base name: "obsTimeLocal")', function() {
        // TODO: update the code to test the property obsTimeLocal
        expect(instance).to.have.property('obsTimeLocal');
        // expect(instance.obsTimeLocal).to.be(expectedValueLiteral);
      });

      it('should have the property obsTimeUtc (base name: "obsTimeUtc")', function() {
        // TODO: update the code to test the property obsTimeUtc
        expect(instance).to.have.property('obsTimeUtc');
        // expect(instance.obsTimeUtc).to.be(expectedValueLiteral);
      });

      it('should have the property solarRadiationHigh (base name: "solarRadiationHigh")', function() {
        // TODO: update the code to test the property solarRadiationHigh
        expect(instance).to.have.property('solarRadiationHigh');
        // expect(instance.solarRadiationHigh).to.be(expectedValueLiteral);
      });

      it('should have the property stationID (base name: "stationID")', function() {
        // TODO: update the code to test the property stationID
        expect(instance).to.have.property('stationID');
        // expect(instance.stationID).to.be(expectedValueLiteral);
      });

      it('should have the property tz (base name: "tz")', function() {
        // TODO: update the code to test the property tz
        expect(instance).to.have.property('tz');
        // expect(instance.tz).to.be(expectedValueLiteral);
      });

      it('should have the property uvHigh (base name: "uvHigh")', function() {
        // TODO: update the code to test the property uvHigh
        expect(instance).to.have.property('uvHigh');
        // expect(instance.uvHigh).to.be(expectedValueLiteral);
      });

      it('should have the property winddirAvg (base name: "winddirAvg")', function() {
        // TODO: update the code to test the property winddirAvg
        expect(instance).to.have.property('winddirAvg');
        // expect(instance.winddirAvg).to.be(expectedValueLiteral);
      });

      it('should have the property qcStatus (base name: "qcStatus")', function() {
        // TODO: update the code to test the property qcStatus
        expect(instance).to.have.property('qcStatus');
        // expect(instance.qcStatus).to.be(expectedValueLiteral);
      });

      it('should have the property imperial (base name: "imperial")', function() {
        // TODO: update the code to test the property imperial
        expect(instance).to.have.property('imperial');
        // expect(instance.imperial).to.be(expectedValueLiteral);
      });

      it('should have the property metric (base name: "metric")', function() {
        // TODO: update the code to test the property metric
        expect(instance).to.have.property('metric');
        // expect(instance.metric).to.be(expectedValueLiteral);
      });

      it('should have the property metricSi (base name: "metric_si")', function() {
        // TODO: update the code to test the property metricSi
        expect(instance).to.have.property('metricSi');
        // expect(instance.metricSi).to.be(expectedValueLiteral);
      });

      it('should have the property ukHybrid (base name: "uk_hybrid")', function() {
        // TODO: update the code to test the property ukHybrid
        expect(instance).to.have.property('ukHybrid');
        // expect(instance.ukHybrid).to.be(expectedValueLiteral);
      });

    });
  });

}));
