<?php
/**
 * MeasuresTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Weather Company PWS API
 *
 * APIs for Personal Weather Station Contributors. This is an unofficial Swagger 2.0 document for working with The Weather Company (Weather Underground) API data. At this time (23-06-2020) this document only covers 2 availible endpoints in observations domain portfolio.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MeasuresTest Class Doc Comment
 *
 * @category    Class
 * @description Measures
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MeasuresTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Measures"
     */
    public function testMeasures()
    {
    }

    /**
     * Test attribute "dewpt"
     */
    public function testPropertyDewpt()
    {
    }

    /**
     * Test attribute "elev"
     */
    public function testPropertyElev()
    {
    }

    /**
     * Test attribute "heat_index"
     */
    public function testPropertyHeatIndex()
    {
    }

    /**
     * Test attribute "precip_rate"
     */
    public function testPropertyPrecipRate()
    {
    }

    /**
     * Test attribute "precip_total"
     */
    public function testPropertyPrecipTotal()
    {
    }

    /**
     * Test attribute "pressure"
     */
    public function testPropertyPressure()
    {
    }

    /**
     * Test attribute "temp"
     */
    public function testPropertyTemp()
    {
    }

    /**
     * Test attribute "wind_chill"
     */
    public function testPropertyWindChill()
    {
    }

    /**
     * Test attribute "wind_gust"
     */
    public function testPropertyWindGust()
    {
    }

    /**
     * Test attribute "wind_speed"
     */
    public function testPropertyWindSpeed()
    {
    }
}
