/*
 * The Weather Company PWS API
 * APIs for Personal Weather Station Contributors. This is an unofficial Swagger 2.0 document for working with The Weather Company (Weather Underground) API data. At this time (24-06-2020) this document only covers 4 availible endpoints in observations domain portfolio.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SummaryMeasures'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SummaryMeasures'));
  } else {
    // Browser globals (root is window)
    if (!root.TheWeatherCompanyPwsApi) {
      root.TheWeatherCompanyPwsApi = {};
    }
    root.TheWeatherCompanyPwsApi.SummariesInner = factory(root.TheWeatherCompanyPwsApi.ApiClient, root.TheWeatherCompanyPwsApi.SummaryMeasures);
  }
}(this, function(ApiClient, SummaryMeasures) {
  'use strict';

  /**
   * The SummariesInner model module.
   * @module model/SummariesInner
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SummariesInner</code>.
   * @alias module:model/SummariesInner
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SummariesInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SummariesInner} obj Optional instance to populate.
   * @return {module:model/SummariesInner} The populated <code>SummariesInner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('epoch'))
        obj.epoch = ApiClient.convertToType(data['epoch'], 'Number');
      if (data.hasOwnProperty('humidityAvg'))
        obj.humidityAvg = ApiClient.convertToType(data['humidityAvg'], 'Number');
      if (data.hasOwnProperty('humidityHigh'))
        obj.humidityHigh = ApiClient.convertToType(data['humidityHigh'], 'Number');
      if (data.hasOwnProperty('humidityLow'))
        obj.humidityLow = ApiClient.convertToType(data['humidityLow'], 'Number');
      if (data.hasOwnProperty('lat'))
        obj.lat = ApiClient.convertToType(data['lat'], 'Number');
      if (data.hasOwnProperty('lon'))
        obj.lon = ApiClient.convertToType(data['lon'], 'Number');
      if (data.hasOwnProperty('obsTimeLocal'))
        obj.obsTimeLocal = ApiClient.convertToType(data['obsTimeLocal'], 'Date');
      if (data.hasOwnProperty('obsTimeUtc'))
        obj.obsTimeUtc = ApiClient.convertToType(data['obsTimeUtc'], 'Date');
      if (data.hasOwnProperty('solarRadiationHigh'))
        obj.solarRadiationHigh = ApiClient.convertToType(data['solarRadiationHigh'], 'Number');
      if (data.hasOwnProperty('stationID'))
        obj.stationID = ApiClient.convertToType(data['stationID'], 'String');
      if (data.hasOwnProperty('tz'))
        obj.tz = ApiClient.convertToType(data['tz'], 'String');
      if (data.hasOwnProperty('uvHigh'))
        obj.uvHigh = ApiClient.convertToType(data['uvHigh'], 'Number');
      if (data.hasOwnProperty('winddirAvg'))
        obj.winddirAvg = ApiClient.convertToType(data['winddirAvg'], 'Number');
      if (data.hasOwnProperty('qcStatus'))
        obj.qcStatus = ApiClient.convertToType(data['qcStatus'], 'Number');
      if (data.hasOwnProperty('imperial'))
        obj.imperial = SummaryMeasures.constructFromObject(data['imperial']);
      if (data.hasOwnProperty('metric'))
        obj.metric = SummaryMeasures.constructFromObject(data['metric']);
      if (data.hasOwnProperty('metric_si'))
        obj.metricSi = SummaryMeasures.constructFromObject(data['metric_si']);
      if (data.hasOwnProperty('uk_hybrid'))
        obj.ukHybrid = SummaryMeasures.constructFromObject(data['uk_hybrid']);
    }
    return obj;
  }

  /**
   * @member {Number} epoch
   */
  exports.prototype.epoch = undefined;

  /**
   * @member {Number} humidityAvg
   */
  exports.prototype.humidityAvg = undefined;

  /**
   * @member {Number} humidityHigh
   */
  exports.prototype.humidityHigh = undefined;

  /**
   * @member {Number} humidityLow
   */
  exports.prototype.humidityLow = undefined;

  /**
   * @member {Number} lat
   */
  exports.prototype.lat = undefined;

  /**
   * @member {Number} lon
   */
  exports.prototype.lon = undefined;

  /**
   * @member {Date} obsTimeLocal
   */
  exports.prototype.obsTimeLocal = undefined;

  /**
   * @member {Date} obsTimeUtc
   */
  exports.prototype.obsTimeUtc = undefined;

  /**
   * @member {Number} solarRadiationHigh
   */
  exports.prototype.solarRadiationHigh = undefined;

  /**
   * @member {String} stationID
   */
  exports.prototype.stationID = undefined;

  /**
   * @member {String} tz
   */
  exports.prototype.tz = undefined;

  /**
   * @member {Number} uvHigh
   */
  exports.prototype.uvHigh = undefined;

  /**
   * @member {Number} winddirAvg
   */
  exports.prototype.winddirAvg = undefined;

  /**
   * Quality control indicator. -1 = No quality control check performed 0 = This observation was marked as possibly incorrect by our quality control algorithm 1 = This observation passed quality control checks
   * @member {Number} qcStatus
   */
  exports.prototype.qcStatus = undefined;

  /**
   * @member {module:model/SummaryMeasures} imperial
   */
  exports.prototype.imperial = undefined;

  /**
   * @member {module:model/SummaryMeasures} metric
   */
  exports.prototype.metric = undefined;

  /**
   * @member {module:model/SummaryMeasures} metricSi
   */
  exports.prototype.metricSi = undefined;

  /**
   * @member {module:model/SummaryMeasures} ukHybrid
   */
  exports.prototype.ukHybrid = undefined;

  return exports;

}));
