/*
 * The Weather Company PWS API
 * APIs for Personal Weather Station Contributors. This is an unofficial Swagger 2.0 document for working with The Weather Company (Weather Underground) API data. At this time (24-06-2020) this document only covers 3 availible endpoints in observations domain portfolio.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheWeatherCompanyPwsApi);
  }
}(this, function(expect, TheWeatherCompanyPwsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheWeatherCompanyPwsApi.PWSDailySummaryApi();
  });

  describe('(package)', function() {
    describe('PWSDailySummaryApi', function() {
      describe('dailySummary7Day', function() {
        it('should call dailySummary7Day successfully', function(done) {
          // TODO: uncomment, update parameter values for dailySummary7Day call and complete the assertions
          /*
          var stationId = "stationId_example";
          var units = "units_example";
          var format = "json";
          var opts = {};
          opts.numericPrecision = "numericPrecision_example";

          instance.dailySummary7Day(stationId, units, format, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TheWeatherCompanyPwsApi.InlineResponse2001);
            expect(data.summaries).to.be.a(TheWeatherCompanyPwsApi.Summaries);
    
            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
